name: Nightly Report to gh-pages

on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC
  workflow_dispatch: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r log_analyzer/requirements.txt
      - name: Generate reports (sample log)
        run: |
          python -m log_analyzer.log_analyzer -f log_analyzer/sample_log.txt -o static
      - name: Commit and deploy static to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          commit_message: "nightly: update static reports"
